using LinQDemo.Data.Models;
using System;

namespace LinQDemo.Data
{
    public class Seeds
    {
        public static City[] Cities => new[]
        {
            new City { Id = 1, Name = "Hà Nội"},
            new City { Id = 2, Name = "Thành phố Hồ Chí Minh" },
            new City { Id = 3, Name = "Bà Rịa" },
            new City { Id = 4, Name = "Bạc Liêu" },
            new City { Id = 5, Name = "Bắc Giang" },
            new City { Id = 6, Name = "Bắc Kạn" },
            new City { Id = 7, Name = "Bắc Ninh" },
            new City { Id = 8, Name = "Bến Tre" },
            new City { Id = 9, Name = "Biên Hòa" },
            new City { Id = 10, Name = "Buôn Ma Thuột" },
            new City { Id = 11, Name = "Cam Ranh" },
            new City { Id = 12, Name = "Cao Bằng" },
            new City { Id = 13, Name = "Cao Lãnh" },
            new City { Id = 14, Name = "Cà Mau" },
            new City { Id = 15, Name = "Cẩm Phả" },
            new City { Id = 16, Name = "Châu Đốc" },
            new City { Id = 17, Name = "Chí Linh" },
            new City { Id = 18, Name = "Đà Lạt" },
            new City { Id = 19, Name = "Điện Biên Phủ" },
            new City { Id = 20, Name = "Đông Hà" },
            new City { Id = 21, Name = "Đồng Hới" },
            new City { Id = 22, Name = "Đồng Xoài" },
            new City { Id = 23, Name = "Hải Dương" },
            new City { Id = 24, Name = "Hà Giang" },
            new City { Id = 25, Name = "Hà Tiên" },
            new City { Id = 26, Name = "Hà Tĩnh" },
            new City { Id = 27, Name = "Hòa Bình" },
            new City { Id = 28, Name = "Hội An" },
            new City { Id = 29, Name = "Huế" },
            new City { Id = 30, Name = "Hưng Yên" },
            new City { Id = 31, Name = "Kon Tum" },
            new City { Id = 32, Name = "Lai Châu" },
            new City { Id = 33, Name = "Lào Cai" },
            new City { Id = 34, Name = "Lạng Sơn" },
            new City { Id = 35, Name = "Long Khánh" },
            new City { Id = 36, Name = "Long Xuyên" },
            new City { Id = 37, Name = "Móng Cái" },
            new City { Id = 38, Name = "Mỹ Tho" },
            new City { Id = 39, Name = "Nam Định" },
            new City { Id = 40, Name = "Nha Trang" },
            new City { Id = 41, Name = "Ninh Bình" },
            new City { Id = 42, Name = "Phan Rang - Tháp Chàm" },
            new City { Id = 43, Name = "Phan Thiết" },
            new City { Id = 44, Name = "Phúc Yên" },
            new City { Id = 45, Name = "Phủ Lý" },
            new City { Id = 46, Name = "Pleiku" },
            new City { Id = 47, Name = "Quảng Ngãi" },
            new City { Id = 48, Name = "Quy Nhơn" },
            new City { Id = 49, Name = "Rạch Giá" },
            new City { Id = 50, Name = "Sóc Trăng" },
            new City { Id = 51, Name = "Sông Công" },
            new City { Id = 52, Name = "Sơn La" },
            new City { Id = 53, Name = "Tam Điệp" },
            new City { Id = 54, Name = "Tam Kỳ" },
            new City { Id = 55, Name = "Tân An" },
            new City { Id = 56, Name = "Tây Ninh" },
            new City { Id = 57, Name = "Thanh Hóa" },
            new City { Id = 58, Name = "Thái Bình" },
            new City { Id = 59, Name = "Thái Nguyên" },
            new City { Id = 60, Name = "Thủ Dầu Một" },
            new City { Id = 61, Name = "Trà Vinh" },
            new City { Id = 62, Name = "Tuyên Quang" },
            new City { Id = 63, Name = "Tuy Hòa" },
            new City { Id = 64, Name = "Uông Bí" },
            new City { Id = 65, Name = "Việt Trì" },
            new City { Id = 66, Name = "Vinh" },
            new City { Id = 67, Name = "Vị Thanh" },
            new City { Id = 68, Name = "Vĩnh Long" },
            new City { Id = 69, Name = "Vĩnh Yên" },
            new City { Id = 70, Name = "Vũng Tàu" },
            new City { Id = 71, Name = "Yên Bái" },
            new City { Id = 72, Name = "Bảo Lộc" },
            new City { Id = 73, Name = "Sa Đéc" },
            new City { Id = 74, Name = "Sầm Sơn" },
            new City { Id = 75, Name = "Hải Phòng" },
            new City { Id = 76, Name = "Đà Nẵng" },
            new City { Id = 77, Name = "Cần Thơ" }
        };

        public static County[] Counties => new[]
        {
            new County { Id = 1, Name = "Ba Đình", CityId = 1, NumberOfCitizens = 247100 },
            new County { Id = 2, Name = "Bắc Từ Liêm", CityId = 1, NumberOfCitizens = 333300 },
            new County { Id = 3, Name = "Cầu Giấy", CityId = 1, NumberOfCitizens = 266800 },
            new County { Id = 4, Name = "Đống Đa", CityId = 1, NumberOfCitizens = 420900 },
            new County { Id = 5, Name = "Hà Đông", CityId = 1, NumberOfCitizens = 352000 },
            new County { Id = 6, Name = "Hai Bà Trưng", CityId = 1, NumberOfCitizens = 318000 },
            new County { Id = 7, Name = "Hoàn Kiếm", CityId = 1, NumberOfCitizens = 160600 },
            new County { Id = 8, Name = "Hoàng Mai", CityId = 1, NumberOfCitizens = 411500 },
            new County { Id = 9, Name = "Long Biên", CityId = 1, NumberOfCitizens = 291900 },
            new County { Id = 10, Name = "Nam Từ Liêm", CityId = 1, NumberOfCitizens = 236700 },
            new County { Id = 11, Name = "Tây Hồ", CityId = 1, NumberOfCitizens = 168300 },
            new County { Id = 12, Name = "Thanh Xuân", CityId = 1, NumberOfCitizens = 285400 },
            new County { Id = 13, Name = "Đồ Sơn", CityId = 75, NumberOfCitizens = 102234 },
            new County { Id = 14, Name = "Dương Kinh", CityId = 75, NumberOfCitizens = 127360 },
            new County { Id = 15, Name = "Hải An", CityId = 75, NumberOfCitizens = 150600 },
            new County { Id = 16, Name = "Hồng Bàng", CityId = 75, NumberOfCitizens = 172310 },
            new County { Id = 17, Name = "Kiến An", CityId = 75, NumberOfCitizens = 120780 },
            new County { Id = 18, Name = "Lê Chân", CityId = 75, NumberOfCitizens = 240150 },
            new County { Id = 19, Name = "Ngô Quyền", CityId = 75, NumberOfCitizens = 208650 },
            new County { Id = 20, Name = "Cẩm Lệ", CityId = 76, NumberOfCitizens = 143632 },
            new County { Id = 21, Name = "Hải Châu", CityId = 76, NumberOfCitizens = 221324 },
            new County { Id = 22, Name = "Liên Chiểu", CityId = 76, NumberOfCitizens = 170153 },
            new County { Id = 23, Name = "Ngũ Hành Sơn", CityId = 76, NumberOfCitizens = 115872 },
            new County { Id = 24, Name = "Sơn Trà", CityId = 76, NumberOfCitizens = 173455 },
            new County { Id = 25, Name = "Thanh Khê", CityId = 76, NumberOfCitizens = 205341 },
            new County { Id = 26, Name = "Bình Thủy", CityId = 77, NumberOfCitizens = 172317 },
            new County { Id = 27, Name = "Cái Răng", CityId = 77, NumberOfCitizens = 165057 },
            new County { Id = 28, Name = "Ninh Kiều", CityId = 77, NumberOfCitizens = 388600 },
            new County { Id = 29, Name = "Ô Môn", CityId = 77, NumberOfCitizens = 160350 },
            new County { Id = 30, Name = "Thốt Nốt", CityId = 77, NumberOfCitizens = 202600 },
            new County { Id = 50, Name = "Cờ Đỏ", CityId = 77, NumberOfCitizens = 135709 },
            new County { Id = 51, Name = "Phong Điền", CityId = 77, NumberOfCitizens = 123136 },
            new County { Id = 52, Name = "Thới Lai", CityId = 77, NumberOfCitizens = 148000 },
            new County { Id = 53, Name = "Vĩnh Thạnh", CityId = 77, NumberOfCitizens = 152200 },
            new County { Id = 31, Name = "Quận 1", CityId = 2, NumberOfCitizens = 205200 },
            new County { Id = 32, Name = "Quận 2", CityId = 2, NumberOfCitizens = 170080 },
            new County { Id = 33, Name = "Quận 3", CityId = 2, NumberOfCitizens = 197600 },
            new County { Id = 34, Name = "Quận 4", CityId = 2, NumberOfCitizens = 203060 },
            new County { Id = 35, Name = "Quận 5", CityId = 2, NumberOfCitizens = 187640 },
            new County { Id = 36, Name = "Quận 6", CityId = 2, NumberOfCitizens = 271050 },
            new County { Id = 37, Name = "Quận 7", CityId = 2, NumberOfCitizens = 324780 },
            new County { Id = 38, Name = "Quận 8", CityId = 2, NumberOfCitizens = 451300 },
            new County { Id = 39, Name = "Quận 9", CityId = 2, NumberOfCitizens = 316450 },
            new County { Id = 40, Name = "Quận 10", CityId = 2, NumberOfCitizens = 372450 },
            new County { Id = 41, Name = "Quận 11", CityId = 2, NumberOfCitizens = 332536 },
            new County { Id = 42, Name = "Quận 12", CityId = 2, NumberOfCitizens = 528170 },
            new County { Id = 43, Name = "Bình Tân", CityId = 2, NumberOfCitizens = 702650 },
            new County { Id = 44, Name = "Bình Thạnh", CityId = 2, NumberOfCitizens = 490380 },
            new County { Id = 45, Name = "Gò Vấp", CityId = 2, NumberOfCitizens = 663313 },
            new County { Id = 46, Name = "Phú Nhuận", CityId = 2, NumberOfCitizens = 181210 },
            new County { Id = 47, Name = "Tân Bình", CityId = 2, NumberOfCitizens = 470350 },
            new County { Id = 48, Name = "Tân Phú", CityId = 2, NumberOfCitizens = 464493 },
            new County { Id = 49, Name = "Thủ Đức", CityId = 2, NumberOfCitizens = 550820 },
        };

        public static School[] Schools => new[]
        {
            new School { Id = 1, CityId = 1, CountyId = 11, Name = "Trường Trung học phổ thông Chu Văn An" },
            new School { Id = 2, CityId = 1, CountyId = 3, Name = "Trường Trung học phổ thông Chuyên Hà Nội - Amsterdam" },
            new School { Id = 3, CityId = 1, CountyId = 3, Name = "Trường Trung học phổ thông Lương Thế Vinh" },
            new School { Id = 4, CityId = 1, CountyId = 3, Name = "Trường Trung học phổ thông Nguyễn Tất Thành" },
            new School { Id = 5, CityId = 1, CountyId = 1, Name = "Trường Trung học phổ thông Phan Đình Phùng" },
            new School { Id = 6, CityId = 1, CountyId = 4, Name = "Trường Trung học phổ thông Quang Trung" },
            new School { Id = 7, CityId = 1, CountyId = 7, Name = "Trường Trung học phổ thông Trần Phú" },
            new School { Id = 8, CityId = 1, CountyId = 7, Name = "Trường Trung học phổ thông Việt Đức" },
            new School { Id = 9, CityId = 1, CountyId = 3, Name = "Trường Trung học phổ thông Chuyên Ngoại ngữ, Đại học Quốc gia Hà Nội" },
            new School { Id = 10, CityId = 1, CountyId = 3, Name = "Trường Trung học phổ thông chuyên Đại học Sư phạm Hà Nội" },
        };

        public static Class[] Classes => new[]
        {
            new Class{ Id = 1, Grade = 10, Name = "10 A1", SchoolId = 1 },
            new Class{ Id = 2, Grade = 10, Name = "10 A2", SchoolId = 1 },
            new Class{ Id = 3, Grade = 10, Name = "10 D1", SchoolId = 1 },
            new Class{ Id = 4, Grade = 10, Name = "10 D2", SchoolId = 1 },
            new Class{ Id = 5, Grade = 10, Name = "10 D3", SchoolId = 1 },
            new Class{ Id = 6, Grade = 11, Name = "11 A1", SchoolId = 1 },
            new Class{ Id = 7, Grade = 11, Name = "11 A2", SchoolId = 1 },
            new Class{ Id = 8, Grade = 11, Name = "11 D1", SchoolId = 1 },
            new Class{ Id = 9, Grade = 11, Name = "11 D2", SchoolId = 1 },
            new Class{ Id = 10, Grade = 11, Name = "11 D3", SchoolId = 1 },
            new Class{ Id = 11, Grade = 12, Name = "12 A1", SchoolId = 1 },
            new Class{ Id = 12, Grade = 12, Name = "12 A2", SchoolId = 1 },
            new Class{ Id = 13, Grade = 12, Name = "12 D1", SchoolId = 1 },
            new Class{ Id = 14, Grade = 12, Name = "12 D2", SchoolId = 1 },
            new Class{ Id = 15, Grade = 12, Name = "12 D3", SchoolId = 1}
        };

        public static Student[] Students => new[]
        {
            new Student { Id = 1, ClassId = 1, SchoolId = 1, FirstName = "No 1", LastName = "Student", DateOfBirth = new DateTime(2014, 5, 8) },
            new Student { Id = 2, ClassId = 1, SchoolId = 1, FirstName = "No 2", LastName = "Student", DateOfBirth = new DateTime(2014, 12, 1) },
            new Student { Id = 3, ClassId = 2, SchoolId = 1, FirstName = "No 3", LastName = "Student", DateOfBirth = new DateTime(2014, 7, 8) },
            new Student { Id = 4, ClassId = 3, SchoolId = 1, FirstName = "No 4", LastName = "Student", DateOfBirth = new DateTime(2014, 3, 23) },
            new Student { Id = 5, ClassId = 4, SchoolId = 1, FirstName = "No 5", LastName = "Student", DateOfBirth = new DateTime(2014, 1, 1) },
            new Student { Id = 6, ClassId = 9, SchoolId = 1, FirstName = "No 6", LastName = "Student", DateOfBirth = new DateTime(2013, 5, 8) },
            new Student { Id = 7, ClassId = 10, SchoolId = 1, FirstName = "No 7", LastName = "Student", DateOfBirth = new DateTime(2013, 12, 1) },
            new Student { Id = 8, ClassId = 9, SchoolId = 1, FirstName = "No 8", LastName = "Student", DateOfBirth = new DateTime(2013, 7, 8) },
            new Student { Id = 9, ClassId = 6, SchoolId = 1, FirstName = "No 9", LastName = "Student", DateOfBirth = new DateTime(2013, 3, 23) },
            new Student { Id = 10, ClassId = 6, SchoolId = 1, FirstName = "No 10", LastName = "Student", DateOfBirth = new DateTime(2013, 1, 1) },
            new Student { Id = 11, ClassId = 12, SchoolId = 1, FirstName = "No 11", LastName = "Student", DateOfBirth = new DateTime(2012, 5, 8) },
            new Student { Id = 12, ClassId = 13, SchoolId = 1, FirstName = "No 12", LastName = "Student", DateOfBirth = new DateTime(2012, 12, 1) },
            new Student { Id = 13, ClassId = 14, SchoolId = 1, FirstName = "No 13", LastName = "Student", DateOfBirth = new DateTime(2012, 7, 8) },
            new Student { Id = 14, ClassId = 14, SchoolId = 1, FirstName = "No 14", LastName = "Student", DateOfBirth = new DateTime(2012, 3, 23) },
            new Student { Id = 15, ClassId = 14, SchoolId = 1, FirstName = "No 15", LastName = "Student", DateOfBirth = new DateTime(2012, 1, 1) },
        };
    }
}
