// <auto-generated />
using System;
using LinQDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinQDemo.Data.Migrations
{
    [DbContext(typeof(LinQDemoContext))]
    partial class LinQDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinQDemo.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thành phố Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bà Rịa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bạc Liêu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bắc Giang"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bắc Kạn"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bến Tre"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Biên Hòa"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Buôn Ma Thuột"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cam Ranh"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Cao Bằng"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Cao Lãnh"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cẩm Phả"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Châu Đốc"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chí Linh"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Đà Lạt"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Điện Biên Phủ"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Đông Hà"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Đồng Hới"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Đồng Xoài"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hải Dương"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hà Giang"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Hà Tiên"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Hòa Bình"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Hội An"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Huế"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Long Khánh"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Long Xuyên"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Móng Cái"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Mỹ Tho"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Nam Định"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Nha Trang"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Phan Rang - Tháp Chàm"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Phan Thiết"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Phúc Yên"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Phủ Lý"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Pleiku"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Quy Nhơn"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Rạch Giá"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Sóc Trăng"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Sông Công"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Tam Điệp"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Tam Kỳ"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Tân An"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Thái Bình"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Thủ Dầu Một"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Trà Vinh"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Tuy Hòa"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Uông Bí"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Việt Trì"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Vinh"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Vị Thanh"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Vĩnh Yên"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Vũng Tàu"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Yên Bái"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Bảo Lộc"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Sa Đéc"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Sầm Sơn"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Cần Thơ"
                        });
                });

            modelBuilder.Entity("LinQDemo.Data.Models.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Grade");

                    b.Property<string>("Name");

                    b.Property<long?>("SchoolId");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Grade = 10,
                            Name = "10 A1",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Grade = 10,
                            Name = "10 A2",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Grade = 10,
                            Name = "10 D1",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Grade = 10,
                            Name = "10 D2",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Grade = 10,
                            Name = "10 D3",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Grade = 11,
                            Name = "11 A1",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Grade = 11,
                            Name = "11 A2",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Grade = 11,
                            Name = "11 D1",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Grade = 11,
                            Name = "11 D2",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Grade = 11,
                            Name = "11 D3",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Grade = 12,
                            Name = "12 A1",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Grade = 12,
                            Name = "12 A2",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Grade = 12,
                            Name = "12 D1",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            Grade = 12,
                            Name = "12 D2",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            Grade = 12,
                            Name = "12 D3",
                            SchoolId = 1L
                        });
                });

            modelBuilder.Entity("LinQDemo.Data.Models.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId");

                    b.Property<string>("Name");

                    b.Property<long>("NumberOfCitizens");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("County");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Ba Đình",
                            NumberOfCitizens = 247100L
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Bắc Từ Liêm",
                            NumberOfCitizens = 333300L
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Cầu Giấy",
                            NumberOfCitizens = 266800L
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Name = "Đống Đa",
                            NumberOfCitizens = 420900L
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Name = "Hà Đông",
                            NumberOfCitizens = 352000L
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Name = "Hai Bà Trưng",
                            NumberOfCitizens = 318000L
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            Name = "Hoàn Kiếm",
                            NumberOfCitizens = 160600L
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            Name = "Hoàng Mai",
                            NumberOfCitizens = 411500L
                        },
                        new
                        {
                            Id = 9,
                            CityId = 1,
                            Name = "Long Biên",
                            NumberOfCitizens = 291900L
                        },
                        new
                        {
                            Id = 10,
                            CityId = 1,
                            Name = "Nam Từ Liêm",
                            NumberOfCitizens = 236700L
                        },
                        new
                        {
                            Id = 11,
                            CityId = 1,
                            Name = "Tây Hồ",
                            NumberOfCitizens = 168300L
                        },
                        new
                        {
                            Id = 12,
                            CityId = 1,
                            Name = "Thanh Xuân",
                            NumberOfCitizens = 285400L
                        },
                        new
                        {
                            Id = 13,
                            CityId = 75,
                            Name = "Đồ Sơn",
                            NumberOfCitizens = 102234L
                        },
                        new
                        {
                            Id = 14,
                            CityId = 75,
                            Name = "Dương Kinh",
                            NumberOfCitizens = 127360L
                        },
                        new
                        {
                            Id = 15,
                            CityId = 75,
                            Name = "Hải An",
                            NumberOfCitizens = 150600L
                        },
                        new
                        {
                            Id = 16,
                            CityId = 75,
                            Name = "Hồng Bàng",
                            NumberOfCitizens = 172310L
                        },
                        new
                        {
                            Id = 17,
                            CityId = 75,
                            Name = "Kiến An",
                            NumberOfCitizens = 120780L
                        },
                        new
                        {
                            Id = 18,
                            CityId = 75,
                            Name = "Lê Chân",
                            NumberOfCitizens = 240150L
                        },
                        new
                        {
                            Id = 19,
                            CityId = 75,
                            Name = "Ngô Quyền",
                            NumberOfCitizens = 208650L
                        },
                        new
                        {
                            Id = 20,
                            CityId = 76,
                            Name = "Cẩm Lệ",
                            NumberOfCitizens = 143632L
                        },
                        new
                        {
                            Id = 21,
                            CityId = 76,
                            Name = "Hải Châu",
                            NumberOfCitizens = 221324L
                        },
                        new
                        {
                            Id = 22,
                            CityId = 76,
                            Name = "Liên Chiểu",
                            NumberOfCitizens = 170153L
                        },
                        new
                        {
                            Id = 23,
                            CityId = 76,
                            Name = "Ngũ Hành Sơn",
                            NumberOfCitizens = 115872L
                        },
                        new
                        {
                            Id = 24,
                            CityId = 76,
                            Name = "Sơn Trà",
                            NumberOfCitizens = 173455L
                        },
                        new
                        {
                            Id = 25,
                            CityId = 76,
                            Name = "Thanh Khê",
                            NumberOfCitizens = 205341L
                        },
                        new
                        {
                            Id = 26,
                            CityId = 77,
                            Name = "Bình Thủy",
                            NumberOfCitizens = 172317L
                        },
                        new
                        {
                            Id = 27,
                            CityId = 77,
                            Name = "Cái Răng",
                            NumberOfCitizens = 165057L
                        },
                        new
                        {
                            Id = 28,
                            CityId = 77,
                            Name = "Ninh Kiều",
                            NumberOfCitizens = 388600L
                        },
                        new
                        {
                            Id = 29,
                            CityId = 77,
                            Name = "Ô Môn",
                            NumberOfCitizens = 160350L
                        },
                        new
                        {
                            Id = 30,
                            CityId = 77,
                            Name = "Thốt Nốt",
                            NumberOfCitizens = 202600L
                        },
                        new
                        {
                            Id = 50,
                            CityId = 77,
                            Name = "Cờ Đỏ",
                            NumberOfCitizens = 135709L
                        },
                        new
                        {
                            Id = 51,
                            CityId = 77,
                            Name = "Phong Điền",
                            NumberOfCitizens = 123136L
                        },
                        new
                        {
                            Id = 52,
                            CityId = 77,
                            Name = "Thới Lai",
                            NumberOfCitizens = 148000L
                        },
                        new
                        {
                            Id = 53,
                            CityId = 77,
                            Name = "Vĩnh Thạnh",
                            NumberOfCitizens = 152200L
                        },
                        new
                        {
                            Id = 31,
                            CityId = 2,
                            Name = "Quận 1",
                            NumberOfCitizens = 205200L
                        },
                        new
                        {
                            Id = 32,
                            CityId = 2,
                            Name = "Quận 2",
                            NumberOfCitizens = 170080L
                        },
                        new
                        {
                            Id = 33,
                            CityId = 2,
                            Name = "Quận 3",
                            NumberOfCitizens = 197600L
                        },
                        new
                        {
                            Id = 34,
                            CityId = 2,
                            Name = "Quận 4",
                            NumberOfCitizens = 203060L
                        },
                        new
                        {
                            Id = 35,
                            CityId = 2,
                            Name = "Quận 5",
                            NumberOfCitizens = 187640L
                        },
                        new
                        {
                            Id = 36,
                            CityId = 2,
                            Name = "Quận 6",
                            NumberOfCitizens = 271050L
                        },
                        new
                        {
                            Id = 37,
                            CityId = 2,
                            Name = "Quận 7",
                            NumberOfCitizens = 324780L
                        },
                        new
                        {
                            Id = 38,
                            CityId = 2,
                            Name = "Quận 8",
                            NumberOfCitizens = 451300L
                        },
                        new
                        {
                            Id = 39,
                            CityId = 2,
                            Name = "Quận 9",
                            NumberOfCitizens = 316450L
                        },
                        new
                        {
                            Id = 40,
                            CityId = 2,
                            Name = "Quận 10",
                            NumberOfCitizens = 372450L
                        },
                        new
                        {
                            Id = 41,
                            CityId = 2,
                            Name = "Quận 11",
                            NumberOfCitizens = 332536L
                        },
                        new
                        {
                            Id = 42,
                            CityId = 2,
                            Name = "Quận 12",
                            NumberOfCitizens = 528170L
                        },
                        new
                        {
                            Id = 43,
                            CityId = 2,
                            Name = "Bình Tân",
                            NumberOfCitizens = 702650L
                        },
                        new
                        {
                            Id = 44,
                            CityId = 2,
                            Name = "Bình Thạnh",
                            NumberOfCitizens = 490380L
                        },
                        new
                        {
                            Id = 45,
                            CityId = 2,
                            Name = "Gò Vấp",
                            NumberOfCitizens = 663313L
                        },
                        new
                        {
                            Id = 46,
                            CityId = 2,
                            Name = "Phú Nhuận",
                            NumberOfCitizens = 181210L
                        },
                        new
                        {
                            Id = 47,
                            CityId = 2,
                            Name = "Tân Bình",
                            NumberOfCitizens = 470350L
                        },
                        new
                        {
                            Id = 48,
                            CityId = 2,
                            Name = "Tân Phú",
                            NumberOfCitizens = 464493L
                        },
                        new
                        {
                            Id = 49,
                            CityId = 2,
                            Name = "Thủ Đức",
                            NumberOfCitizens = 550820L
                        });
                });

            modelBuilder.Entity("LinQDemo.Data.Models.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId");

                    b.Property<int?>("CountyId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CityId = 1,
                            CountyId = 11,
                            Name = "Trường Trung học phổ thông Chu Văn An"
                        },
                        new
                        {
                            Id = 2L,
                            CityId = 1,
                            CountyId = 3,
                            Name = "Trường Trung học phổ thông Chuyên Hà Nội - Amsterdam"
                        },
                        new
                        {
                            Id = 3L,
                            CityId = 1,
                            CountyId = 3,
                            Name = "Trường Trung học phổ thông Lương Thế Vinh"
                        },
                        new
                        {
                            Id = 4L,
                            CityId = 1,
                            CountyId = 3,
                            Name = "Trường Trung học phổ thông Nguyễn Tất Thành"
                        },
                        new
                        {
                            Id = 5L,
                            CityId = 1,
                            CountyId = 1,
                            Name = "Trường Trung học phổ thông Phan Đình Phùng"
                        },
                        new
                        {
                            Id = 6L,
                            CityId = 1,
                            CountyId = 4,
                            Name = "Trường Trung học phổ thông Quang Trung"
                        },
                        new
                        {
                            Id = 7L,
                            CityId = 1,
                            CountyId = 7,
                            Name = "Trường Trung học phổ thông Trần Phú"
                        },
                        new
                        {
                            Id = 8L,
                            CityId = 1,
                            CountyId = 7,
                            Name = "Trường Trung học phổ thông Việt Đức"
                        },
                        new
                        {
                            Id = 9L,
                            CityId = 1,
                            CountyId = 3,
                            Name = "Trường Trung học phổ thông Chuyên Ngoại ngữ, Đại học Quốc gia Hà Nội"
                        },
                        new
                        {
                            Id = 10L,
                            CityId = 1,
                            CountyId = 3,
                            Name = "Trường Trung học phổ thông chuyên Đại học Sư phạm Hà Nội"
                        });
                });

            modelBuilder.Entity("LinQDemo.Data.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ClassId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<long?>("SchoolId");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClassId = 1L,
                            DateOfBirth = new DateTime(2014, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 1",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ClassId = 1L,
                            DateOfBirth = new DateTime(2014, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 2",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ClassId = 2L,
                            DateOfBirth = new DateTime(2014, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 3",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            ClassId = 3L,
                            DateOfBirth = new DateTime(2014, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 4",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            ClassId = 4L,
                            DateOfBirth = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 5",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            ClassId = 9L,
                            DateOfBirth = new DateTime(2013, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 6",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            ClassId = 10L,
                            DateOfBirth = new DateTime(2013, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 7",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            ClassId = 9L,
                            DateOfBirth = new DateTime(2013, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 8",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            ClassId = 6L,
                            DateOfBirth = new DateTime(2013, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 9",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            ClassId = 6L,
                            DateOfBirth = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 10",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            ClassId = 12L,
                            DateOfBirth = new DateTime(2012, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 11",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            ClassId = 13L,
                            DateOfBirth = new DateTime(2012, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 12",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            ClassId = 14L,
                            DateOfBirth = new DateTime(2012, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 13",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            ClassId = 14L,
                            DateOfBirth = new DateTime(2012, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 14",
                            LastName = "Student",
                            SchoolId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            ClassId = 14L,
                            DateOfBirth = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "No 15",
                            LastName = "Student",
                            SchoolId = 1L
                        });
                });

            modelBuilder.Entity("LinQDemo.Data.Models.Class", b =>
                {
                    b.HasOne("LinQDemo.Data.Models.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LinQDemo.Data.Models.County", b =>
                {
                    b.HasOne("LinQDemo.Data.Models.City", "City")
                        .WithMany("Counties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LinQDemo.Data.Models.School", b =>
                {
                    b.HasOne("LinQDemo.Data.Models.City", "City")
                        .WithMany("Schools")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinQDemo.Data.Models.County", "County")
                        .WithMany("Schools")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LinQDemo.Data.Models.Student", b =>
                {
                    b.HasOne("LinQDemo.Data.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.HasOne("LinQDemo.Data.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
